#define MAINPREFIX z
#define PREFIX afl
#define PROJECT_PREFIX 62STB
#define SUBPREFIX addons

#define PATHTO_SYS(var1,var2,var3) \MAINPREFIX\PROJECT_PREFIX\SUBPREFIX\DOUBLES(var1,var2)\var3.sqf
#define PATHTOF_SYS(var1,var2,var3) \MAINPREFIX\PROJECT_PREFIX\SUBPREFIX\DOUBLES(var1,var2)\var3
#define PATHTOF2_SYS(var1,var2,var3) MAINPREFIX\PROJECT_PREFIX\SUBPREFIX\DOUBLES(var1,var2)\var3

#define DEBUG_MODE_FULL

#include "script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH
#define VERSION_AR  MAJOR,MINOR,PATCH,BUILD

#define VERSION_CONFIG version = VERSION; versionStr = QUOTE(MAJOR.MINOR.PATCH); versionAr[] = {VERSION_AR}

#define REQUIRED_VERSION 2.20
#define REQUIRED_CBA_VERSION {3, 18, 4}
#define REQUIRED_ACE_VERSION {3, 20, 0}
#define REQUIRED_KAM_VERSION {3, 1, 2}

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(AFL - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(AFL - COMPONENT)
#endif
